version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_REPOSITORY_DIR}:/srv/www/repository-files
    environment:
      APP_ENV: production
