version: '3.2'

services:
  app:
    image: $APP_IMAGE
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./repository:/srv/app/www/repository-files
    ports:
      - :80
    env_file: app.env
