version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ${APP_REPOSITORY_DIRECTORY}:/srv/app/www/repository-files
    ports:
      - :80
    env_file: ${APP_ENV_FILE}
